version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-3-101.compute-1.amazonaws.com
            port: '5432'
            database: d6930rhsdapid7
            ssl: true
            user: eiepzbvelmhdwg
            password: 771277fe0d84827f0b532c7ede709cf2cafa875a0609d9d6367d124f33670e39
            migrations: true